language:
  - c
  - cpp
  
matrix:
  include:
  - os: linux
    dist: xenial
    compiler:
      - gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - cmake
          - cmake-data
    script:
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7
      - gcc -v && g++ -v && cmake --version
      - mkdir -p build/
      - cd build/
      - cmake ../
      - cmake --build .
  - os: osx
    osx_image: xcode11.5
    compiler:
      - gcc
    addons:
      homebrew:
        packages:
          - cmake
    script:
      - mkdir -p build/
      - cd build/
      - cmake ../
      - cmake --build .
  - os: windows
    compiler:
      - gcc
    script:
      - choco install make
      - choco install cmake
      - mkdir build/
      - cd build/
      - cmake ../
      - cmake --build .
